name: Generate GithubPages Action
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate_github_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Github Pages
        run: |
          make install_generate_mkdocs
          git config --global user.name "github-actions:bot"
          git add -A
          git commit -m "docs: auto generate mkdoc files"
          git push
